$ANSIBLE_VAULT;1.1;AES256
37313761376165626638313237323531326536643262623137336263303861303761666266643731
6566336634663332356236323638646238376533386139640a353538653134663337373131346365
62633236653537346664623765366666636634343836333439333561313166616436326533393561
3063613364646665380a623632643737303362363833303235333137613930626332353538356162
37376365336534633866646239646333303130373166643664363033373437333139316663343064
62343862636234306235666530353838623631363163323533353432626361383262636462393039
30663830623834626237326362613030333061626130333561343863646338616431363464656466
61663733633233346331613263386335663438653032623863656536646337633566323935636530
30383831613639353365626335336665653966333366386262656334613663363639383735393262
65313430303631363365386532396561363330353031306638623134653866323137366337306435
38653830313964363532353233663434373430373133373561366433313135333831643530633365
63623461326461333062333663343063643863626433313637346335316132393235316537303931
33343038316138656437326132663362386231363862343966393762393632653632373664663930
62656563623437396665333431396139386134383439306562353134343430646261323136316663
366232363865356433383232306632313237
