---
# Variables pour l'installation
system_package_list:
  - vim
  - git
  - htop
  - curl
  - wget

# Installer les paquets essentiels sur les PVE
- name: Installer les paquets essentiels
  ansible.builtin.apt:
    name: "{{ system_package_list }}"
    state: present
    update_cache: true
  when: "'pve' in group_names"

