---
# Installer les paquets uniquement sur les PVE
- name: Installer les paquets système sur PVE
  ansible.builtin.import_tasks: install.yml
  when: "'pve' in group_names"

# Mettre à jour tous les systèmes (PVE et VMs)
- name: Mettre à jour tous les systèmes
  ansible.builtin.import_tasks: update.yml

